#!/bin/bash
###############################################################################
# vasp_dry_run.sh   (invoked on PATH as: vasp-dry-run)
#
# Submit a one-rank VASP dry run to your cluster's DEBUG partition. The
# resulting OUTCAR feeds vasp_recommend_slurm.py (vasp-recommend-slurm), which
# uses it to predict memory and suggest the best parallelization setup.
#
# CLUSTER PROFILE
#   Partition, notification email and the VASP module(s) to load all come from
#   the profile written by `vasp-configure` (~/.config/wolfpack-dft/cluster.conf).
#   If no profile exists, built-in NLHPC defaults are used.
#
# WHAT IT DOES
#   Renders a SELF-CONTAINED job script (slurm_dryrun.sh) with the resolved
#   #SBATCH directives and module-load lines baked in, writes it to the current
#   directory so the exact job is on disk for inspection even if it crashes,
#   and submits it. The job runs "vasp_std --dry-run" on 1 MPI rank: VASP
#   initialises all arrays, writes its memory table to OUTCAR, then exits.
#
# USAGE
#   cd <dir with INCAR / POSCAR / POTCAR / KPOINTS>
#   vasp-dry-run            # writes ./slurm_dryrun.sh and submits it
#   # (sbatch vasp-dry-run also works, but uses the cluster's default partition)
#
# PART OF: dry-run / parallelization workflow
#   Step 1: vasp-dry-run                   <-- THIS SCRIPT
#   Step 2: vasp-recommend-slurm OUTCAR
###############################################################################
#SBATCH --job-name=vasp_dryrun
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH -c 1
#SBATCH --mem-per-cpu=8000
#SBATCH -t 00:30:00
#SBATCH -o vasp_dryrun_%j.out
#SBATCH -e vasp_dryrun_%j.err
# (the normal entry point `vasp-dry-run` renders slurm_dryrun.sh instead; these
#  in-file directives apply only if you run `sbatch vasp-dry-run` directly.)

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    sed -n '2,28p' "${BASH_SOURCE[0]}" | grep -v '^#####' | sed 's/^# \{0,1\}//'
    exit 0
fi

set -uo pipefail

# --- Load the cluster profile (if present) --------------------------------- #
_wp_conf="${WOLFPACK_CLUSTER_CONF:-$HOME/.config/wolfpack-dft/cluster.conf}"
# shellcheck source=/dev/null
[[ -f "$_wp_conf" ]] && source "$_wp_conf"

# Emit the resolved module-load command lines (single source of truth: used both
# to bake them into the rendered job script and to load them in the fallback).
_wp_module_block() {
    if [[ -n "${WP_VASP_MODULES:-}" ]]; then
        local cmd="${WP_MODULE_CMD:-ml}"
        if [[ "${WP_MODULE_PURGE:-1}" == "1" ]]; then
            [[ "$cmd" == "module" ]] && echo "module purge" || echo "ml purge"
        fi
        if [[ "$cmd" == "module" ]]; then echo "module load ${WP_VASP_MODULES}"
        else echo "ml ${WP_VASP_MODULES}"; fi
    else                                   # built-in NLHPC default
        echo "ml purge"
        echo "ml gcc/14.2.0-zen4-y"
        echo "ml vasp/6.4.3-mpi-openmp-h5-zen4-c"
    fi
}

# --- Submit side: render a self-contained job script and submit it --------- #
if [[ -z "${SLURM_JOB_ID:-}" ]]; then
    if ! command -v sbatch >/dev/null 2>&1; then
        echo "ERROR: sbatch not found. Run this on a cluster login node." >&2
        exit 1
    fi
    part="${WP_DEBUG_PARTITION:-debug}"
    exe="${WP_VASP_STD:-vasp_std}"
    job="$PWD/slurm_dryrun.sh"
    {
        echo "#!/bin/bash"
        echo "#SBATCH --job-name=vasp_dryrun"
        echo "#SBATCH --partition=${part}"
        echo "#SBATCH --ntasks=1"
        echo "#SBATCH --ntasks-per-node=1"
        echo "#SBATCH --cpus-per-task=1"
        echo "#SBATCH --mem-per-cpu=8000"
        echo "#SBATCH --time=00:30:00"
        if [[ -n "${WP_EMAIL:-}" ]]; then
            echo "#SBATCH --mail-user=${WP_EMAIL}"
            echo "#SBATCH --mail-type=ALL"
        fi
        echo "#SBATCH --output=vasp_dryrun_%j.out"
        echo "#SBATCH --error=vasp_dryrun_%j.err"
        echo ""
        echo "# Generated by vasp-dry-run on $(date -Iseconds) -- the exact job submitted."
        echo 'cd "$SLURM_SUBMIT_DIR"'
        echo ""
        echo "# --- modules (resolved from your cluster profile) ---"
        _wp_module_block
        echo ""
        echo "srun -n 1 ${exe} --dry-run"
    } > "$job"
    chmod +x "$job"
    echo "Wrote job script : $job" >&2
    echo "Submitting 1-rank VASP dry run to partition '${part}' ..." >&2
    exec sbatch "$job"
fi

# --- Direct-sbatch fallback (`sbatch vasp-dry-run`): run the dry run inline -- #
cd "$SLURM_SUBMIT_DIR" || exit 1
while IFS= read -r _ml; do eval "$_ml" 2>/dev/null || true; done < <(_wp_module_block)
srun -n 1 "${WP_VASP_STD:-vasp_std}" --dry-run
